spring:
  application:
    name: zuul-server
server:
  port: 8762
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefereIpAddress: true
  serviceurl:
    defaultzone: http://localhost:8761/eureka/
